/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidffmpeg_MainActivity */

#ifndef _Included_com_example_androidffmpeg_MainActivity
#define _Included_com_example_androidffmpeg_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidffmpeg_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidffmpeg_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidffmpeg_MainActivity
 * Method:    StringForAVcode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidffmpeg_MainActivity_StringForAVcode
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidffmpeg_MainActivity
 * Method:    StringForAVutil
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidffmpeg_MainActivity_StringForAVutil
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidffmpeg_MainActivity
 * Method:    StringForAVformat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidffmpeg_MainActivity_StringForAVformat
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidffmpeg_MainActivity
 * Method:    StringForAVfilter
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidffmpeg_MainActivity_StringForAVfilter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
